version: '3.8'
services:
  go-app:
    build: .
    #image: bernardolankheet/zabbix-easy:latest
    container_name: go-zabbix-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zabbix_report
      - MAX_CCONCURRENT=13
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ZABBIX_SERVER_HOSTID=10084 # HostID do zabbix Server, utliza para pegar os dados de performance.
      #- ZABBIX_SERVER_HOSTID=23423
      - APP_DEBUG=1 # Habilita logs de debug da API do Zabbix
      - CHECKTRENDTIME=15d # Tempo para verificar tendência de dados (0 desabilita), leva em consideracão o valor que é definido no zabbix para Trends ou o Valor Utilizado no Particionamento do banco de dados.
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: go-zabbix-postgres
    environment:
      POSTGRES_DB: zabbix_report
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: go-zabbix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
