services:
  go-app:
    #build: ./app # Uncomment the line above to build the image locally, or use the ready-made image on Docker Hub.
    image: bernardolankheet/zabbix-easy:latest
    container_name: go-zabbix-app
    ports:
      - "8080:8080"
    environment:
      # Uncomment the variables below to enable report persistence in PostgreSQL.
      # To start with the database: docker compose --profile db up --build -d
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=zabbix_report
      - MAX_CCONCURRENT=10 # Defines the maximum number of concurrent processes to process Zabbix data, adjust according to your environment's capacity.
      - API_TIMEOUT_SECONDS=20   # Used in frontend environments with low performance, increases the timeout for Zabbix API response.
      - ZABBIX_SERVER_HOSTID=10084 # HostID of the Zabbix Server, used to fetch performance data.
      - APP_DEBUG=true # true or false Enables debug logs for the Zabbix API
      - CHECKTRENDTIME=15d # Time to check data trends, do not use history (<7d), takes into account the value defined in Zabbix for Trends or the value used in database partitioning.
    restart: unless-stopped
# To start with the database: docker compose --profile db up --build -d    
  postgres:
    profiles: ["db"]
    image: postgres:18-alpine
    container_name: go-zabbix-postgres
    environment:
      POSTGRES_DB: zabbix_report
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d zabbix_report"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-data:
    name: go_zabbix_postgres_data