site_name: Zabbix Easy Report
repo_url: https://github.com/bernardolankheet/zabbix-easy
nav:
  - Home: index.md
  - Novidades: changes.md
  - Instalação: instalacao.md
  - API: api.md
  - Docker: docker.md
  - Utilização: utilizacao.md
  - Contribuição: contribuicao.md
theme:
  name: material
  language: pt
plugins:
  - search
markdown_extensions:
  - admonition
extra_javascript:
  - js/mermaid.min.js
  - js/mermaid-init.js
  - js/lang-switch.js
extra_css:
  - css/lang-switch.css
