site_name: Zabbix Easy Report
repo_url: https://github.com/bernardolankheet/zabbix-easy
repo_name: bernardolankheet/zabbix-easy
site_description: "Zabbix Easy Report is a open-source tool that analyzes a Zabbix environment via API and generates a HealthCheck report with practical recommendations to improve performance, reliability, and maintenance."
site_url: https://zabbix-easy.github.io
site_author: Bernardo Lankheet
copyright: Copyright &copy; 2026 Maintained by <a href="https://github.com/bernardolankheet">Bernardo Lankheet</a>.
nav:
  - Home: index.md
  - Installation: pt_BR/installation.md
  - Usage: pt_BR/usage.md
  - API: pt_BR/api.md
  - Screenshots: pt_BR/screenshots.md
  - Changelog: https://github.com/bernardolankheet/zabbix-easy/blob/main/CHANGELOG.md
  - Contribution: pt_BR/contribution.md  
theme:
  name: material
  language: pt
  favicon: img/favicon.svg
  logo: img/favicon.svg
plugins:
  - search
markdown_extensions:
  - admonition
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
  - js/lang-switch.js
extra_css:
  - css/lang-switch.css