{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix-easy.postgresHost" . }}
  labels:
    {{- include "zabbix-easy.labels" . | nindent 4 }}
    component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: postgres
    spec:
      terminationGracePeriodSeconds: {{ .Values.spec.terminationGracePeriodSeconds }}
      containers:
      - name: postgres
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: {{ .Values.db.name | quote }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "zabbix-easy.dbSecret" . }}
              key: DB_USER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "zabbix-easy.dbSecret" . }}
              key: DB_PASSWORD
              optional: false
        {{- if .Values.postgres.resources }}
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        {{- end }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                # try a fast but clean shutdown of Postgres
                pg_ctl -D ${PGDATA:-/var/lib/postgresql/data} -m fast stop || true
                sleep 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ include "zabbix-easy.postgresHost" . }}-pvc
{{- end }}
