{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zabbix-easy.postgresHost" . }}-pvc
  labels:
    {{- include "zabbix-easy.labels" . | nindent 4 }}
    component: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClassName }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
  {{- end }}
{{- end }}
