{{- if .Values.objects.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zabbix-easy.dbSecret" . }}
  labels:
    {{- include "zabbix-easy.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
{{- end }}
